mysite/applications/derivatives/urls.py
from django.urls import path
from . import views

#TEMPLATE TAGGING
app_name = "derivatives"

urlpatterns = [
    path("g20_dashboard/", views.derivatives, name = "derivatives"),
    path("custom_data/", views.custom_data, name = "custom_data"),
    path("custom_data/compare_contrast/", views.compare_contrast, name = "compare_contrast"),
    path("custom_data/gdp_per_cap_report/", views.gdp_per_cap_report, name = "gdp_per_cap_report"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.main.urls')),
    path('', include('applications.derivatives.urls')),
]

mysite/applications/derivatives/models.py
from django.db import models

# Create your models here.
class EconomicIndicatorStandard(models.Model):
    date = models.DateField()
    dbcode = models.CharField(max_length=100)
    indicator = models.CharField(max_length=200)
    country = models.CharField(max_length=20)
    freq = models.CharField(max_length=10)
    value = models.FloatField(null=False, blank=False, default=None)
    update_date = models.DateField(null=True)
    flow = models.CharField(max_length=1)

    class Meta:
        unique_together = (("date", "dbcode", "freq"),)

    def __str__(self):
        return self.dbcode + '_' + self.indicator + '_' + self.country

class EconomicIndicatorCounterparty(models.Model):
    date = models.DateField()
    dbcode = models.CharField(max_length=100)
    indicator = models.CharField(max_length=200)
    country = models.CharField(max_length=20)
    counter_party = models.CharField(max_length=20)
    freq = models.CharField(max_length=10)
    value = models.FloatField(null=False, blank=False, default=None)
    update_date = models.DateField(null=True)

    class Meta:
        unique_together = (("date", "dbcode", "freq", "counter_party"),)
    def __str__(self):
        return self.dbcode + '_' + self.indicator + '_' + self.country

mysite/applications/derivatives/views.py
from django.shortcuts import render
import json
from applications.derivatives.project_code.Downlaod_Dbnomics_API_Data import DownloadDbnomicsAPIData
from applications.derivatives.project_code.Economic_Indicator_Dashboard import EconomicIndicatorDashboard
from applications.derivatives.project_code.Single_Timeseries import SingleTimeSeries
import pandas as pd


# Create your views here.
def derivatives(request):
    country_list = list(DownloadDbnomicsAPIData().country_code.keys())

    if request.method == 'POST':
        country = request.POST['country_list']
        freq = request.POST['freq']
        start_year = request.POST['start_year']
        end_year = request.POST['end_year']

        context = create_context(country_list, country, freq, start_year, end_year)

        return render(request=request,
                      template_name = 'derivatives_base.html',
                      context = context)
    else:
        return render(request=request, template_name = 'derivatives_base.html', context={"country_list": country_list,})

def custom_data(request):
    return render(request=request, template_name = 'custom_data.html')

def gdp_per_cap_report(request):
    indicator_display_list = SingleTimeSeries().get_display_names()
    TS = SingleTimeSeries()
    indicator = 'Debt - Household & NPISHs (% GDP)'
    date = None
    x_axis = 'Real GDP per Capita (USD)'
    title = ""

    if request.method == 'POST':
        indicator = request.POST['indicator_display_list']
        date = request.POST['date']
        date_a, date_b = get_proper_dates(date, date)
        date = date_b

    l = []
    if x_axis != "None" and indicator != "None":
        df_a = TS.get_timeseries_multiple_countries(x_axis, date=date)
        df_b = TS.get_timeseries_multiple_countries(indicator, date=date)
        l = [df_a, df_b]

        title = indicator + ' Comparison by ' + x_axis

    if l:
        df = pd.concat(l, axis=1, sort=False)
        df = df.dropna()
        df.index.name = "Country"
        df.reset_index(inplace=True)
        df = df.pivot(index=x_axis, columns='Country', values=indicator)
        df = df.copy()
        df.reset_index(inplace=True)
        cols = list(df.columns)
        df = df[cols]
        result = [df.columns.values.tolist()] + df.values.tolist()

    else:
        result = []

    return render(request=request, template_name = 'gdp_per_cap_report.html',
    context={"indicator_display_list": indicator_display_list, 'gdp_comp_data': json.dumps(result),
    'title': title})


def compare_contrast(request):
    country_list = SingleTimeSeries().get_g20_countries()
    indicator_display_list = SingleTimeSeries().get_display_names()
    TS = SingleTimeSeries()

    country_1 = "United States"
    country_2 = "Canada"
    indicator_1 = 'Debt - Household & NPISHs (% GDP)'
    indicator_2 = 'Debt - Household & NPISHs (% GDP)'
    start_date = None
    end_date = None
    freq = None

    if request.method == 'POST':
        country_1 = request.POST['country_list_1']
        indicator_1 = request.POST['indicator_display_list_1']
        country_2 = request.POST['country_list_2']
        indicator_2 = request.POST['indicator_display_list_2']
        freq = request.POST['freq']
        start_date, end_date = get_proper_dates(request.POST['start_year'],  request.POST['end_year'])

    l = []

    if country_1 != "None" and indicator_1 != "None":
        l.append(TS.get_timeseries(country_1, indicator_1, start_date, end_date, freq))
    if country_2 != "None" and indicator_2 != "None":
        l.append(TS.get_timeseries(country_2, indicator_2, start_date, end_date, freq))

    if l:
        df = pd.concat(l, axis=1)
        title = ' VS. '.join(df.columns.values.tolist())
        df.reset_index(inplace=True)
        df = df.copy()
        df['Date'] = df['Date'].apply(lambda x: x.strftime('%Y-%m'))
        result = [df.columns.values.tolist()] + df.values.tolist()
    else:
        title = ""
        result = []

    return render(request=request, template_name = 'compare_contrast.html',
    context={"country_list": country_list,
    "indicator_display_list": indicator_display_list,
    'custom_data': json.dumps(result),
    "title": title,})

def get_proper_dates(start_year, end_year):
    try:
        start_year = int(start_year)
        if start_year >=1900 and start_year <= 2100:
            start_year = start_year
        else:
            start_year = 1990
    except:
        start_year = 1990
    start_date = str(start_year) + '-01-01'

    try:
        end_year = int(end_year)
        if end_year >=1900 and end_year <= 2100:
            end_year = end_year
        else:
            end_year = 2100
        end_date = str(end_year) + '-12-31'
        if end_year < start_year:
            end_date = None
    except:
        end_date = None

    return start_date, end_date




def create_context(country_list, country, freq, start_year, end_year):

    start_date, end_date = get_proper_dates(start_year, end_year)
    ER = EconomicIndicatorDashboard(country, start_date, end_date, freq, True, False)
    # rep_dic = ER.multiple_pool_report()

    use_pool = False

    if use_pool:
        gdpData = rep_dic["1"]
    else:
        gdpData = ER.real_gdp_lcu()

    if use_pool:
        gdpGrowthContribution = rep_dic["2"]
    else:
        gdpGrowthContribution = ER.real_gdp_growth_contribution()

    if use_pool:
        cpi_growth = rep_dic["3"]
    else:
        cpi_growth = ER.cpi_all_item_growth()

    if use_pool:
        cpi_basket_items_growth = rep_dic["4"]
    else:
        cpi_basket_items_growth = ER.cpi_basket_items_growth()

    if use_pool:
        populationLabourForce = rep_dic["5"]
    else:
        populationLabourForce = ER.wdi_population_labour()

    if use_pool:
        populationLabourForceGrowth = rep_dic["6"]
    else:
        populationLabourForceGrowth = ER.wdi_population_labour_growth()

    if use_pool:
        unemploymentRate = rep_dic["7"]
    else:
        unemploymentRate = ER.ifs_unemployment_rate()

    if use_pool:
        bopInfo = rep_dic["8"]
    else:
        bopInfo = ER.bop_info()

    if use_pool:
        currAccBreakdown = rep_dic["9"]
    else:
        currAccBreakdown = ER.bop_curr_acc_breakdown()

    if use_pool:
        finAccBreakdown = rep_dic["10"]
    else:
        finAccBreakdown = ER.bop_fin_acc_breakdown()

    if use_pool:
        tradeBal = rep_dic["11"]
    else:
        tradeBal = ER.dot_trade_bal()

    if use_pool:
        tradeBalG20Countries = rep_dic["12"]
    else:
        tradeBalG20Countries = ER.dot_trade_bal_g20countries()

    if use_pool:
        servNetExpBreakdown = rep_dic["13"]
    else:
        servNetExpBreakdown = ER.bop_services_breakdown()

    if use_pool:
        goodNetExpBreakdown = rep_dic["14"]
    else:
        goodNetExpBreakdown = ER.wto_goods_breakdown()

    if use_pool:
        tradePriceIndex = rep_dic["15"]
    else:
        tradePriceIndex = ER.ifs_trade_price_index()

    if use_pool:
        fdiAssetsLiabilities = rep_dic["16"]
    else:
        fdiAssetsLiabilities = ER.bop_fdi_assets_liabilities()

    if use_pool:
        portfolioAssetsLiabilities = rep_dic["17"]
    else:
        portfolioAssetsLiabilities = ER.bop_portfolio_assets_liabilities()

    if use_pool:
        portfolioAssetsMinusLiabilities = rep_dic["18"]
    else:
        portfolioAssetsMinusLiabilities = ER.bop_portfolio_investment_assetsMinusLiabilities()

    if use_pool:
        portfolioInvCP = rep_dic["19"]
    else:
        portfolioInvCP = ER.portfolio_inv_cp()

    if use_pool:
        reserveAssetsBreakdown = rep_dic["20"]
    else:
        reserveAssetsBreakdown = ER.bop_reserve_assets_breakdown()

    if use_pool:
        oecdTenYThreeMYield = rep_dic["21"]
    else:
        oecdTenYThreeMYield = ER.oecd_10y_3m_yield()

    if use_pool:
        effectiveExchangeRates = rep_dic["22"]
    else:
        effectiveExchangeRates = ER.effective_exchange_rates()

    if use_pool:
        porpertyIndex = rep_dic["23"]
    else:
        porpertyIndex = ER.property_price_index()

    if use_pool:
        debtRatio = rep_dic["24"]
    else:
        debtRatio = ER.debt_ratio()

    context = {"country_list": country_list,
    "real_gdp": {"data": json.dumps(gdpData)},
    "real_gdp_growth_contribution":{"data": json.dumps(gdpGrowthContribution)},
    "cpi_growth": {"data": json.dumps(cpi_growth)},
    "cpi_basket_items_growth":{"data": json.dumps(cpi_basket_items_growth)},
    "population_labour_force": {"data": json.dumps(populationLabourForce)},
    "population_labour_force_growth": {"data": json.dumps(populationLabourForceGrowth)},
    "unemployment_rate": {"data": json.dumps(unemploymentRate)},
    "bop_info": {"data": json.dumps(bopInfo)},
    "curr_acc_breakdown": {"data": json.dumps(currAccBreakdown)},
    "fin_acc_breakdown": {"data": json.dumps(finAccBreakdown)},
    "trade_bal": {"data": json.dumps(tradeBal)},
    "trade_bal_g20countries": {"data": json.dumps(tradeBalG20Countries)},
    "serv_net_exp_breakdown": {"data": json.dumps(servNetExpBreakdown)},
    "good_net_exp_breakdown": {"data": json.dumps(goodNetExpBreakdown)},
    "trade_price_index": {"data": json.dumps(tradePriceIndex)},
    "fdi_assets_liabilities": {"data": json.dumps(fdiAssetsLiabilities)},
    "portfolio_assets_liabilities": {"data": json.dumps(portfolioAssetsLiabilities)},
    "portfolio_inv_CP": {"data": json.dumps(portfolioInvCP)},
    "portfolio_assets_minus_liabilities": {"data": json.dumps(portfolioAssetsMinusLiabilities)},
    "reserve_assets_breakdown": {"data": json.dumps(reserveAssetsBreakdown)},
    "oecd_ten_y_three_m_yield": {"data": json.dumps(oecdTenYThreeMYield)},
    "effective_exchange_rates": {"data": json.dumps(effectiveExchangeRates)},
    "porperty_index": {"data": json.dumps(porpertyIndex)},
    "debt_ratio": {"data": json.dumps(debtRatio)},
    }

    return context

mysite/applications/derivatives/templates/compare_contrast.html
{% extends "index.html" %}

<!-- title -->
{% block title %}
<title>Compare and Contrast</title>
{% endblock %}


{% block content %}

<section id="main" >

	<div class="inner">

		<header class="major special">
			<header>
					<h2>Compare and Contrast</h2>
			</header>
		</header>
		<body>

			<form action="{{country}}" method="post" class="form-disable">
				{% csrf_token %}

				<div class="row">
					<div class="3u 1u$(xsmall)">
						<div class="select-wrapper">
							<select name="country_list_1" id="country_list_1">
								<option value="None"> - Select Country 1 - </option>
								{% for country in country_list %}
									<option value="{{country}}">{{country}}</option>
								{% endfor %}
							</select>
						</div>
					</div>
					<div class="5u 1u$(xsmall)">
						<div class="select-wrapper">
							<select name="indicator_display_list_1" id="indicator_display_list_1">
								<option value="None">Indicator1:</option>
								{% for indicator in indicator_display_list %}
									<option value="{{indicator}}">{{indicator}}</option>
								{% endfor %}
							</select>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="3u 1u$(xsmall)">
						<div class="select-wrapper">
							<select name="country_list_2" id="country_list_2">
								<option value="None">- Select Country 2 -</option>
								{% for country in country_list %}
									<option value="{{country}}">{{country}}</option>
								{% endfor %}
							</select>
						</div>
					</div>
					<div class="5u 1u$(xsmall)">
						<div class="select-wrapper">
							<select name="indicator_display_list_2" id="indicator_display_list_2">
								<option value="None">Indicator2:</option>
								{% for indicator in indicator_display_list %}
									<option value="{{indicator}}">{{indicator}}</option>
								{% endfor %}
							</select>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="2u 1u$(xsmall)">
						<div class="select-wrapper">
							<select name="freq" id="freq">
								<option value="A">- Frequency -</option>
									<option value="A">Annual</option>
									<option value="Q">Quarterly</option>
							</select>
						</div>
					</div>

					<div class="2u 5u(xsmall)">
						<input type="text" placeholder="Start Year: YYYY" name="start_year" id="start_year"/>
					</div>

					<div class="2u 5u(xsmall)">
						<input type="text" placeholder="End Year: YYYY" name="end_year" id="end_year" />
					</div>

					<div class="3u 8u(xsmall)">
						<ul class="actions">
							<li><input href="#" type='submit' value="Run Report" class="button alt"></button></li>
						</ul>
					</div>
				</div>
			</form>

		</body>
	</div>

</section>

<section id="main" >
	<div class="inner">
		<h6>&nbsp;&nbsp;&nbsp;&nbsp;{{title}}</h6>
	</div>
	<script>var custom_data = {{custom_data|safe}};</script>
	<div id = "custom_data"></div>
</section>

{% endblock %}

mysite/applications/derivatives/templates/custom_data.html
{% extends "index.html" %}

<!-- title -->
{% block title %}
<title>Custom Data</title>
{% endblock %}


{% block content %}

<section id="main" >

	<div class="inner">

		<header class="major special">
			<header>
        <h2>Customized Reports: </h2>
      </header>

		</header>

		<section>
			<h3>Compare & Contrast</h3>
			<p>Select any timeseries data to visualize in a line chart. Users may compare two different economic indicators for one country to find cause and effect relationship or make a comparison between two countries for a selected indicator.</p>
			<ul class="actions">
				<li><a href="{% url 'derivatives:compare_contrast' %}" class="button alt">Learn More</a></li>
			</ul>
			<hr />

			<h3>GDP per Capita Comparison</h3>
			<p>Select an economic indicator to visualize in a scatter plot and understand G20 countries' economy with respect to GDP per Capita. An interesting example to see is how Household Debt to GDP increases as GDP per Capita increases.</p>
			<ul class="actions">
				<li><a href="{% url 'derivatives:gdp_per_cap_report' %}" class="button alt">Learn More</a></li>
			</ul>
			<hr />

			<h3>Trade Data Dashboard</h3>
			<p>This page is currently under development. Sorry for your inconvenience.</p>
			<ul class="actions">
				<li><a href="" class="button alt">Learn More</a></li>
			</ul>
			<hr />

			<h3>Investment Data Dashboard</h3>
			<p>This page is currently under development. Sorry for your inconvenience.</p>
			<ul class="actions">
				<li><a href="" class="button alt">Learn More</a></li>
			</ul>
			<hr />

		</section>


	</div>
	<br>
	<br>
</section>
{% endblock %}

mysite/applications/derivatives/templates/derivatives_base.html
{% extends "index.html" %}

<!-- title -->
{% block title %}
<title>G20 Dashboard</title>
{% endblock %}


{% block content %}

<section id="main" >

	<div class="inner">

		<header class="major special">
			<header>
					<h2>G20 Countries Economic Indicators</h2>
			</header>
			<p>Note: Please select a country and click 'Run Report'. It should take about 10 seconds to load.</p>
		</header>

		<body>

			<form action="{{country}}" method="post" class="form-disable">
				{% csrf_token %}

				<div class="row">

					<div class="3u 1u$(xsmall)">
						<div class="select-wrapper">
							<select name="country_list" id="country_list">
								<option value="United States">- Please Select a Country -</option>
								{% for country in country_list %}
									<option value="{{country}}">{{country}}</option>
								{% endfor %}
							</select>
						</div>
					</div>

					<div class="2u 1u$(xsmall)">
						<div class="select-wrapper">
							<select name="freq" id="freq">
								<option value="A">- Frequency -</option>
									<option value="A">Annual</option>
									<option value="Q">Quarterly</option>
							</select>
						</div>
					</div>

					<div class="2u 5u(xsmall)">
						<input type="text" placeholder="Start Year (YYYY)" name="start_year" id="start_year"/>
					</div>

					<div class="2u 5u(xsmall)">
						<input type="text" placeholder="End Year (YYYY)" name="end_year" id="end_year" />
					</div>

					<div class="3u 8u(xsmall)">
						<ul class="actions">
							<li><input href="#" type='submit' value="Run Report" class="button alt"></button></li>
						</ul>
					</div>
				</div>
			</form>


		</body>
	</div>

</section>


<section id="four">
	

	<div class="inner">
		<div class="content">
			<div class="5u">
				<script>var real_gdp_data = {{real_gdp.data|safe}};</script>
				<div id = "real_gdp"></div>
			</div>
		</div>
		<div class="content">
			<div class="5u">
				<script>var gdp_growth_contribution_data = {{real_gdp_growth_contribution.data|safe}};</script>
				<div id = "real_gdp_breakdown"></div>
			</div>
		</div>
	</div>

	<div class="inner">
		<div class="content">
			<div class="5u">
				<script>var cpi_growth_data = {{cpi_growth.data|safe}};</script>
				<div id = "cpi_growth"></div>
			</div>
		</div>
		<div class="content">
			<div class="5u">
				<script>var cpi_basket_items_growth_data = {{cpi_basket_items_growth.data|safe}};</script>
				<div id = "cpi_basket_items_growth"></div>
			</div>
		</div>
	</div>

	<div class="inner">
		<div class="content">
			<div class="5u">
				<script>var population_labour_force_data = {{population_labour_force.data|safe}};</script>
				<div id = "population_labour_force"></div>
			</div>
		</div>
		<div class="content">
			<div class="5u">
				<script>var population_labour_force_growth_data = {{population_labour_force_growth.data|safe}};</script>
				<div id = "population_labour_force_growth"></div>
			</div>
		</div>
	</div>

	<div class="inner">
		<div class="content">
			<div class="5u">
				<script>var unemployment_rate_data = {{unemployment_rate.data|safe}};</script>
				<div id = "unemployment_rate"></div>
			</div>
		</div>
		<div class="content">
		</div>
	</div>

	<div class="inner">
		<div class="content">
			<div class="5u">
				<script>var bop_info_data = {{bop_info.data|safe}};</script>
				<div id = "bop_info"></div>
			</div>
		</div>
	</div>

	<div class="inner">
		<div class="content">
			<div class="5u">
				<script>var curr_acc_breakdown_data = {{curr_acc_breakdown.data|safe}};</script>
				<div id = "curr_acc_breakdown"></div>
			</div>
		</div>
		<div class="content">
			<div class="5u">
				<script>var fin_acc_breakdown_data = {{fin_acc_breakdown.data|safe}};</script>
				<div id = "fin_acc_breakdown"></div>
			</div>
		</div>
	</div>

	<div class="inner">
		<div class="content">
			<div class="5u">
				<script>var trade_bal_data = {{trade_bal.data|safe}};</script>
				<div id = "trade_bal"></div>
			</div>
		</div>
		<div class="content">
			<div class="5u">
				<script>var trade_bal_g20_data = {{trade_bal_g20countries.data|safe}};</script>
				<div id = "trade_bal_g20"></div>
			</div>
		</div>
	</div>

	<div class="inner">
		<div class="content">
			<div class="5u">
				<script>var serv_net_exp_breakdown_data = {{serv_net_exp_breakdown.data|safe}};</script>
				<div id = "serv_net_exp_breakdown"></div>
			</div>
		</div>
		<div class="content">
			<div class="5u">
				<script>var good_net_exp_breakdown_data = {{good_net_exp_breakdown.data|safe}};</script>
				<div id = "good_net_exp_breakdown"></div>
			</div>
		</div>
	</div>

	<div class="inner">
		<div class="content">
			<div class="5u">
				<script>var trade_price_index_data = {{trade_price_index.data|safe}};</script>
				<div id = "trade_price_index"></div>
			</div>
		</div>
		<div class="content">
			<div class="5u">
				<script>var effective_exchange_rates_data = {{effective_exchange_rates.data|safe}};</script>
				<div id = "effective_exchange_rates"></div>
			</div>
		</div>
	</div>

	<div class="inner">
		<div class="content">
			<div class="5u">
				<script>var fdi_asset_liability_data = {{fdi_assets_liabilities.data|safe}};</script>
				<div id = "fdi_asset_liability"></div>
			</div>
		</div>
		<div class="content">
			<div class="5u">
				<script>var portfolio_asset_liability_data = {{portfolio_assets_liabilities.data|safe}};</script>
				<div id = "portfolio_asset_liability"></div>
			</div>
		</div>
	</div>

	<div class="inner">
		<div class="content">
			<div class="5u">
				<script>var portfolio_assets_minus_liabilities_data = {{portfolio_assets_minus_liabilities.data|safe}};</script>
				<div id = "portfolio_assets_minus_liabilities"></div>
			</div>
		</div>
		<div class="content">
			<div class="5u">
				<script>var portfolio_inv_CP_data = {{portfolio_inv_CP.data|safe}};</script>
				<div id = "portfolio_inv_CP"></div>
			</div>
		</div>
	</div>

	<div class="inner">
		<div class="content">
			<div class="5u">
				<script>var reserve_assets_breakdown_data = {{reserve_assets_breakdown.data|safe}};</script>
				<div id = "reserve_assets_breakdown"></div>
			</div>
		</div>
		<div class="content">
			<div class="5u">
				<script>var oecd_ten_y_three_m_yield_data = {{oecd_ten_y_three_m_yield.data|safe}};</script>
				<div id = "oecd_ten_y_three_m_yield"></div>
			</div>
		</div>
	</div>

	<div class="inner">
		<div class="content">
			<div class="5u">
				<script>var porperty_index_data = {{porperty_index.data|safe}};</script>
				<div id = "porperty_index"></div>
			</div>
		</div>
		<div class="content">
			<div class="5u">
				<script>var debt_ratio_data = {{debt_ratio.data|safe}};</script>
				<div id = "debt_ratio"></div>
			</div>
		</div>
	</div>


</section>


{% endblock %}

mysite/applications/derivatives/templates/gdp_per_cap_report.html
{% extends "index.html" %}

<!-- title -->
{% block title %}
<title>Comparison by GDP per Capita</title>
{% endblock %}


{% block content %}

<section id="main" >

	<div class="inner">

		<header class="major special">
			<header>
					<h2>Comparison by GDP per Capita Chart:</h2>
			</header>
		</header>
		<body>

			<form action="{{country}}" method="post" class="form-disable">
				{% csrf_token %}

				<div class="row">

					<div class="4u 1u$(xsmall)">
						<div class="select-wrapper">
							<select name="indicator_display_list" id="indicator_display_list">
								<option value="None">Select an Indicator</option>
								{% for indicator in indicator_display_list %}
									<option value="{{indicator}}">{{indicator}}</option>
								{% endfor %}
							</select>
						</div>
					</div>

					<div class="3u 1u(xsmall)">
						<input type="text" placeholder="Year: YYYY" name="date" id="date"/>
					</div>

					<div class="3u 8u(xsmall)">
						<ul class="actions">
							<li><input href="#" type='submit' value="Run Report" class="button alt"></button></li>
						</ul>
					</div>
				</div>
			</form>

		</body>
	</div>

</section>


<section id="main" >
	<div class="inner">
		<h6>{{title}}</h6>
	</div>
	<script>var gdp_comp_data = {{gdp_comp_data|safe}};</script>
	<div id = "gdp_comp_data"></div>
</section>


{% endblock %}