mysite/applications/derivatives/urls.py
from django.urls import path
from . import views

#TEMPLATE TAGGING
app_name = "derivatives"

urlpatterns = [
    path("g20_dashboard/", views.derivatives, name = "derivatives"),
    path("custom_data/", views.custom_data, name = "custom_data"),
    path("custom_data/compare_contrast/", views.compare_contrast, name = "compare_contrast"),
    path("custom_data/gdp_per_cap_report/", views.gdp_per_cap_report, name = "gdp_per_cap_report"),
]

mysite/applications/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.main, name = "main"),
    path("contact/", views.emailView, name = "contact"),
    path("contact/sent/", views.successView, name = "sent"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.main.urls')),
    path('', include('applications.derivatives.urls')),
]

mysite/templates/include/footer.html
<section id="footer">
  <div class="inner">
    <div class="copyright">
      © 2019 S. Nam,
      Template Designed by: <a href="https://templated.co/"> &copy; TEMPLATED</a>,
      Data Source: <a href="https://www.quandl.com/">Quandl</a>,
      <a href="https://db.nomics.world/">DBnomics</a>
    </div>
  </div>
</section>

mysite/templates/include/nav.html
<header id="header">
  <div class="inner">
    <a href="{% url 'main:main' %}" class="logo">The Countrynomics</a>
    <nav id="nav">
      <a href="{% url 'derivatives:derivatives' %}">G20 Dashboard</a>
      <a href="{% url 'derivatives:custom_data' %}">Custom Report</a>
      <a href="{% url 'main:contact' %}">Contact</a>
    </nav>
  </div>
</header>
<a href="#menu" class="navPanelToggle"><span class="fa fa-bars"></span></a>